apiVersion: v1
kind: Pod
metadata:
  name: ncr-nginx-pod
spec:
  imagePullSecrets:
    - name: registry-credential
  containers:
    - name: web
      image: {사용자 레지스트리 주소}/nginx:1.14.2
      ports:
        - name: web
          containerPort: 80
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"