apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-1
spec:
  selector:
    matchLabels:
      app: example-1
  template:
    metadata:
      labels:
        app: example-1
    spec:
      containers:
      - name: example-1
        image: nginx:1.24.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
